### ISSUE TITLE
Plugin error when adding browserifyoptions tsify in index.js

### ISSUE THREAD

**Issue by dexsans** [TheBrainFamily/cypress-cucumber-preprocessor#109]
Hi,

I followed everything in https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#typescript so my plugins/index.js contained:

const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require("@cypress/browserify-preprocessor");

module.exports = (on) => {
    const options = browserify.defaultOptions;

    options.browserifyOptions.plugin.unshift(['tsify']);
    // Or, if you need a custom tsconfig.json for your test files:
    //options.browserifyOptions.plugin.unshift(['tsify', {project: '../../tsconfig.json'}]);

    on('file:preprocessor', cucumber(options))
}

But when I run my test tthrough a feature file with a .ts step definition, an error occurs in cypress:

 Error running plugin
The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.

Error: ENOENT: no such file or directory, lstat 'C:\xxx\xxx\xxx\cypress\integration\integration\integration'
at realpathSync (fs.js:1669:15)
at fs.realpathSync (ELECTRON_ASAR.js:320:29)
at Function.realpathSync (C:\xxx\xxx\xxx\node_modules\fs.realpath\index.js:48:12)
at C:\xxx\xxx\xxx\node_modules\tsify\index.js:78:44
at Array.map (native)
at DestroyableTransform.flush [as _flush] (C:\xxx\xxx\xxx\node_modules\tsify\index.js:78:6)
at DestroyableTransform.prefinish (C:\xxx\xxx\xxx\node_modules\readable-stream\lib\_stream_transform.js:138:10)
at emitNone (events.js:105:13)
at DestroyableTransform.emit (events.js:207:7)
at prefinish (C:\xxx\xxx\xxx\node_modules\readable-stream\lib\_stream_writable.js:619:14)
at finishMaybe (C:\xxx\xxx\xxx\node_modules\readable-stream\lib\_stream_writable.js:627:5)
at endWritable (C:\xxx\xxx\xxx\node_modules\readable-stream\lib\_stream_writable.js:638:3)
at DestroyableTransform.Writable.end (C:\xxx\xxx\xxx\node_modules\readable-stream\lib\_stream_writable.js:594:41)
at DestroyableTransform.onend (C:\xxx\xxx\xxx\node_modules\readable-stream\lib\_stream_readable.js:577:10)
at Object.onceWrapper (events.js:314:30)
at emitNone (events.js:110:20)
at DestroyableTransform.emit (events.js:207:7)
at endReadableNT (C:\xxx\xxx\xxx\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)

But if I remove this particular line in my code: options.browserifyOptions.plugin.unshift(['tsify']);
Then my test executes but when I try to use "import", the error: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' occurs.

Am I missing a plugin for tsify to work since I just need to use "import" in my .ts files?

**Comment by lgandecki** [comment]
We now have an example for typescript working with webpack:
Hello, sorry for taking a long time to responde.

We now have examples for using TypeScript with Webpack:

https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/

and without it:

https://github.com/TheBrainFamily/cypress-cucumber-typescript-example/


I'm closing this thread for now, if you have a specific issue, after verifying that the examples work, and that your configuration is in line with them, or if you need to somehow configure things differently - please create a new one and I will be glad to take a look.
