### ISSUE TITLE
expect assertions in steps being called before feature run

### ISSUE THREAD

**Issue by zhammer** [TheBrainFamily/cypress-cucumber-preprocessor#150]
having a weird issue where any `expect`s in my step definitions are executed before my actual feature is executed. (i don't know how to run `cypress-cucumber-preprocessor` with debug logs so i'm not sure if this is happening in preprocessing or at the start of the test run)

i added `expect(2).to.equal(2)` to the `When` step definitions and confirmed that that assertion also runs at the start of the test.

i have two other spec files that have been working fine, but all of their assertions are via `cy.get("button").should("contain", "this text")` style assertions.

#### `SettingsPage.feature`
```feature
Feature: Settings Page

  Scenario: Logging out
    Given I am logged in
    And I am on the settings page
    When I click the button that says "Log out"
    Then I am redirected to the login page
    And my login information is gone
```

#### `SettingsPage/steps.js`
```js
/// <reference types="cypress" />

import { Given, Then, When } from "cypress-cucumber-preprocessor/steps";

beforeEach(() => {
  cy.clearLocalStorage();
});

Given("I am logged in", () => {
  localStorage.setItem("accessToken", "cypress_access_token");
});

Given("I am on the settings page", () => {
  cy.visit("/settings");
});

When(`I click the button that says {string}`, buttonText => {
  cy.get("button")
    .contains(buttonText)
    .click();
});

Then("I am redirected to the login page", () => {
  cy.location("pathname").should("eq", "/login");
});

Then("my login information is gone", () => {
  expect(localStorage.getItem("accessToken")).to.be.null;
});
```

#### `yarn run cypress run` log
```
Zachs-MBP:one-thing zhammer$ yarn run cypress run --spec cypress/integration/SettingsPage.feature 
yarn run v1.13.0
$ /Users/zhammer/code/one-thing/node_modules/.bin/cypress run --spec cypress/integration/SettingsPag
e.feature

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.5                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      1 found (SettingsPage.feature)                                                     │
  │ Searched:   cypress/integration/SettingsPage.feature                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: SettingsPage.feature...                                                         (1 of 1) 


  Settings Page
    1) Logging out


  0 passing (227ms)
  1 failing

  1) Settings Page Logging out:
     AssertionError: expected 'cypress_access_token' to be null
      at Context.runnable.fn (http://localhost:5000/__cypress/runner/cypress_runner.js:61323:20)
      at callFn (http://localhost:5000/__cypress/runner/cypress_runner.js:30429:21)
      at Test.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:30422:7)
      at http://localhost:5000/__cypress/runner/cypress_runner.js:64243:28
      at PassThroughHandlerContext.finallyHandler (http://localhost:5000/__cypress/runner/cypress_ru
nner.js:123873:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:5000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:5000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:5000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:5000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:5000/__cypress/runner/cypress_runner.js:125394:18)
      at Async._drainQueue (http://localhost:5000/__cypress/runner/cypress_runner.js:122119:16)
      at Async._drainQueues (http://localhost:5000/__cypress/runner/cypress_runner.js:122129:10)
      at Async.drainQueues (http://localhost:5000/__cypress/runner/cypress_runner.js:122003:14)
      at <anonymous>




  (Results)

  ┌────────────────────────────────────┐
  │ Tests:        1                    │
  │ Passing:      0                    │
  │ Failing:      1                    │
  │ Pending:      0                    │
  │ Skipped:      0                    │
  │ Screenshots:  1                    │
  │ Video:        true                 │
  │ Duration:     0 seconds            │
  │ Spec Ran:     SettingsPage.feature │
  └────────────────────────────────────┘


  (Screenshots)

  - /Users/zhammer/code/one-thing/cypress/screenshots/SettingsPage.feature/Settings Page -- Logging out (failed).png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/zhammer/code/one-thing/cypress/videos/SettingsPage.feature.mp4 (0 seconds)


====================================================================================================

  (Run Finished)


      Spec                                                Tests  Passing  Failing  Pending  Skipped 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  ¯│ ✖ SettingsPage.feature                      217ms        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    1 of 1 failed (100%)                        217ms        1        -        1        -        -  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lgandecki** [comment]
This is how cypress works - in the first run it queues the events (created with cy API), and after that it actually fires the event from the queues.
Try cy.then(() => { expect(localStorage.getItem("accessToken")).to.be.null; }), although I'm not sure if you will get the correct localStorage that way, that's a different story. In general, please ask cypress specific questions in cypress related places :-)
