### ISSUE TITLE
I get this error when I run cypress after installing this preprocessor

### ISSUE THREAD

**Issue by MRolandd** [TheBrainFamily/cypress-cucumber-preprocessor#449]
I have used this in the past and it worked fine.
But now I get this error from the library. I tried installing an older version but the same thing.
```
/node_modules/@cypress/browserify-preprocessor/node_modules/fs-extra/lib/remove/rimraf.js:305
      } catch {}
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/httpd/localhost/partners_cypress_tests/httpd/cypress-testing-11-cypress-scenario-testing-with-react-frontend-server/cypress-tests/node_modules/@cypress/browserify-preprocessor/node_modules/fs-extra/lib/remove/index.js:4:16)
    at Object.<anonymous> (/home/httpd/localhost/partners_cypress_tests/httpd/cypress-testing-11-cypress-scenario-testing-with-react-frontend-server/cypress-tests/node_modules/@cypress/browserify-preprocessor/node_modules/fs-extra/lib/remove/index.js:11:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/httpd/localhost/partners_cypress_tests/httpd/cypress-testing-11-cypress-scenario-testing-with-react-frontend-server/cypress-tests/node_modules/@cypress/browserify-preprocessor/node_modules/fs-extra/lib/empty/index.js:7:16)
    at Object.<anonymous> (/home/httpd/localhost/partners_cypress_tests/httpd/cypress-testing-11-cypress-scenario-testing-with-react-frontend-server/cypress-tests/node_modules/@cypress/browserify-preprocessor/node_modules/fs-extra/lib/empty/index.js:50:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
```

**Comment by lgandecki** [comment]
it's an error coming from fs-extra as you can see, since they ar eusing the syntax for catch without specyfing a list of zero arguments. I'm guessing you are using an old (and possibly unsopported) nodejs version, could you doublecheck?

**Comment by MRolandd** [comment]
> it's an error coming from fs-extra as you can see, since they ar eusing the syntax for catch without specyfing a list of zero arguments. I'm guessing you are using an old (and possibly unsopported) nodejs version, could you doublecheck?

I just checked and installed the latest node js release (14.12.0)  But I still get the same error

**Comment by lgandecki** [comment]
are you sure that's the one you use for running cypress though?
as googling  suggests, the problem should indeed go away with nodejs >=10 
https://github.com/jprichardson/node-fs-extra/issues/771
https://github.com/jprichardson/node-fs-extra/pull/794

**Comment by MRolandd** [comment]
I've installed NVM. I uninstalled all other npm versions. I ran 
```
nvm use 14.12.0
```

And I still get the same error

**Comment by MRolandd** [comment]
Solved. The problem was that I had an older version of cypress
