### ISSUE TITLE
Cannot run e2e test with docker

### ISSUE THREAD

**Issue by engmagdy87** [TheBrainFamily/cypress-cucumber-preprocessor#460]
### Current behavior

E2E test cannot be run on Docker as it fires the following error
```sh
No version of Cypress is installed in: /root/.cache/Cypress/3.8.3/Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: /root/.cache/Cypress/3.8.3/Cypress/Cypress

----------

Platform: linux (Raspbian - )
Cypress Version: 3.8.3
 ERROR  Error: Command failed: /app/node_modules/cypress/bin/cypress open --config baseUrl=http://localhost:8080/
Error: Command failed: /app/node_modules/cypress/bin/cypress open --config baseUrl=http://localhost:8080/
    at makeError (/app/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/app/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ***@0.1.0 test:e2e: `vue-cli-service test:e2e`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ***@0.1.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-20T00_46_25_483Z-debug.log

```
### Desired behavior

E2E run
### Versions

* **Cypress version**: 3.8.3
* **Preprocessor version**:4.0.0
* **Node version**:12.13.0

**Comment by lgandecki** [comment]
Can you try with just cypress? It seems like this would be unrelated to our preprocessor.
