### ISSUE TITLE
Typescript support is not working for Cypress

### ISSUE THREAD

**Issue by GRmeB** [TheBrainFamily/cypress-cucumber-preprocessor#657]
### Current behavior

I'm working on Mac OS 12.0.1 and I have an issue working with the typescript support. If I use the code for integrating the typescript support, then I will get an error message when starting the cypress tests in open and in run mode.

So, I hope you have a running solution for me. On an old Windows 7 VM with Node v11 it is running, but not on Mac OS X.

**cypress/support/index.ts**
```
/**
 * @type {Cypress.PluginConfig}
 */
const browserify = require('@cypress/browserify-preprocessor');
const cucumber = require('cypress-cucumber-preprocessor').default;
const resolve = require('resolve');
const fs = require('fs-extra');

require('dotenv').config();

import * as path from 'path';
import { defaultsDeep } from 'lodash';

function getPath(app: string, file: string) {
    return path.resolve('..', 'config', 'applications', app, file);
}

async function getConfigurationByFile(app: string, file: string) {
    const pathToAppConfigFile = getPath(app, 'cypress.json');

    const pathToEnvironmentConfigFile = app.startsWith('bp')
        ? getPath('bp', `cypress.${file}.json`)
        : getPath(app, `cypress.${file}.json`);

    const apiCredentials = {
        env: {
            credentials: {
                apiBasicAuth:
                    process.env[
                        `API_CREDENTIALS_${file
                            .toUpperCase()
                            .replace('-', '_')}`
                    ],
            },
        },
    };

    return defaultsDeep(
        await fs.readJson(pathToEnvironmentConfigFile),
        await fs.readJson(pathToAppConfigFile),
        apiCredentials
    );
}

// @ts-ignore
module.exports = (on, config) => {
    const options = {
        ...browserify.defaultOptions,
        // ---> HERE I'M GETTING THE ERROR <---
        typescript: resolve.sync('typescript', { baseDir: config.projectRoot }),
    };

    on('file:preprocessor', cucumber(options));

    // @ts-ignore
    on('after:spec', (spec, results) => {
        if (results.stats.failures === 0 && results.video) {
            return fs.remove(results.video);
        }
    });

    // accept a configFile value or use local development by default
    const file = config.env.configFile || 'local';
    return getConfigurationByFile(config.env.app, file);
};
```

**And this is the error message:**
```
TypeError: Cannot read property 'uid' of undefined
    at Object.statSync (/Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:303:17)
    at isDirectory (/Users/GRme/projects/github/testframework/node_modules/.pnpm/resolve@1.21.0/node_modules/resolve/lib/sync.js:22:23)
    at loadNodeModulesSync (/Users/GRme/projects/github/testframework/node_modules/.pnpm/resolve@1.21.0/node_modules/resolve/lib/sync.js:191:17)
    at Function.resolveSync [as sync] (/Users/GRme/projects/github/testframework/node_modules/.pnpm/resolve@1.21.0/node_modules/resolve/lib/sync.js:98:17)
    at module.exports (/Users/GRme/projects/github/testframework/cypress/plugins/index.ts:63:29)
    at /Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:90:12
    at tryCatcher (/Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:87:7)
    at EventEmitter.<anonymous> (/Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:198:5)
    at EventEmitter.emit (events.js:400:28)
    at process.<anonymous> (/Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:400:28)
    at process.emit (/Users/GRme/Library/Caches/Cypress/9.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:912:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

### Desired behavior

I want the tests are running with typescript support.

### Test code to reproduce

Please see above :)

### Versions

* **Cypress version**: tried with 8.7.0, 9.0.0 and 9.2.0
* **Preprocessor version**: tried with 4.1.1 and 4.3.0
* **Node version**: tried with Node 12@latest, 14@latest and 16@latest

I've tried all possible combinations on Macbook Pro with M1 Chip and on Macbook Pro without M1 chip, but nothing was running.

**Cypress 8.5.0 is the latest version that is running with that support. So, from version 8.6.0 it is not running anymore.**

**Comment by sirganya** [comment]
Same problem here. I had to revert to 8.5.0.

**Comment by GRmeB** [comment]
But I've found a solution make it running again. So, it is more a documentation issue and maybe the documentation should be updated. The `config.projectRoot`variable value seems to be different since Cypress version 8.6.0. So the `resolve.sync()`function gets an invalid path for searching for `typescript`.

You can solve this issue while replacing the code with the following one:
```
    const options = {
        ...browserify.defaultOptions,

        //old version, that is not running anymore
        //typescript: resolve.sync('typescript', { baseDir: config.projectRoot }),

        //new version, that is running for me
        typescript: path.join(path.resolve('..'), 'node_modules/typescript'),
    };

    on('file:preprocessor', cucumber(options));
```

**Comment by lgandecki** [comment]
@GRmeB  Thanks for the tip! Would you mind sending a PR to update the Readme.md ? :-)

**Comment by GRmeB** [comment]
@lgandecki I've created a very little PR :) https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/658

**Comment by sirganya** [comment]
Thanks for the fix.
I think it may not be a one size fits all. I had to change the path of the typescript module to find it in my setup.

**Comment by GRmeB** [comment]
@sirganya the fix is prepared for the setup setting the path in the `cypress/plugins/index.js` and hosting the node modules under `<project_root>/node_modules`. If you have another setup then you have to update the path that it is running for you. So, please feel free to extend the documentation with these useful information :)

**Comment by sirganya** [comment]
I have the same setup.

**Comment by GRmeB** [comment]
PR #658 with documentation fix is already merged.

**Comment by kasztof** [comment]
Is this bugfix still not released?

**Comment by badeball** [comment]
Which fix are you referring to?

**Comment by kasztof** [comment]
This PR: https://github.com/badeball/cypress-cucumber-preprocessor/pull/658. I didn't realise it's just update of the docs.. Anyway, on [npm](https://www.npmjs.com/package/cypress-cucumber-preprocessor#typeScript-support), there is still the old version, which doesn't work

**Comment by badeball** [comment]
The package has moved: https://github.com/badeball/cypress-cucumber-preprocessor/issues/689

**Comment by kasztof** [comment]
Ah, okay! Thanks
