### ISSUE TITLE
Typescript integration and common steps gives Dependency graph error

### ISSUE THREAD

**Issue by danbord** [TheBrainFamily/cypress-cucumber-preprocessor#674]
I took the example provided here : https://github.com/TheBrainFamily/cypress-cucumber-typescript-example

I just added a simple step file in **cypress/integration/common/common.ts**

File content is just a simple step
```
import { Given } from "cypress-cucumber-preprocessor/steps/index";

Given(/I initialize/, () => {
    console.log("INITIALIZE")
  });
```
```
When executing the feature, I get the following error:

Error: Can't walk dependency graph: Cannot find module 'cypress-cucumber-preprocessor/steps/index' from 'C:\GIT\cypress-cucumber-typescript-example\cypress-cucumber-typescript-example\cypress\integration\common\common.ts'
    required by C:\GIT\cypress-cucumber-typescript-example\cypress-cucumber-typescript-example\cypress\integration\common\common.ts
    at C:\GIT\cypress-cucumber-typescript-example\cypress-cucumber-typescript-example\node_modules\resolve\lib\async.js:146:35
    at processDirs (C:\GIT\cypress-cucumber-typescript-example\cypress-cucumber-typescript-example\node_modules\resolve\lib\async.js:299:39)
    at isdir (C:\GIT\cypress-cucumber-typescript-example\cypress-cucumber-typescript-example\node_modules\resolve\lib\async.js:306:32)
    at C:\GIT\cypress-cucumber-typescript-example\cypress-cucumber-typescript-example\node_modules\resolve\lib\async.js:34:69
    at callback (C:\Users\danie_o306gx1\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:192:21)
```

### Versions

* **Cypress version**: v8.7.0
* **Preprocessor version**: v4.3.1
* **Node version**: v16.13.0

**Comment by danbord** [comment]
Nevermind, the problem was with the import.  Changing it from
`import { Given } from "cypress-cucumber-preprocessor/steps/index";`
to 
`import { Given } from "cypress-cucumber-preprocessor/steps/index";`
fixed the problem
