### ISSUE TITLE
TypeError: cosmiconfig is not a function

### ISSUE THREAD

**Issue by WinstonN** [TheBrainFamily/cypress-cucumber-preprocessor#683]
### Current behavior
Following the instructions, and installing the cypress-cucumber-preprocessor throws an error when I launch cypress, and click on a `.feature` file

Seems like a pretty simple error and because of that I am not 100% why this has not been reported. It could be related to my system (WSL2 on Windows)

```bash
TypeError: cosmiconfig is not a function
    at exports.getConfig (/project/node_modules/cypress-cucumber-preprocessor/lib/getConfig.js:7:16)
    at module.exports (/project/node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.js:7:18)
    at Object.handler (/project/node_modules/cypress-cucumber-preprocessor/lib/index.js:78:16)
    at invoke (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:22:16)
    at /home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/util.js:45:14
    at tryCatcher (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/util.js:44:23)
    at Object.wrap (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/preprocessor.js:28:8)
    at execute (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:119:27)
    at EventEmitter.<anonymous> (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:209:5)
    at EventEmitter.emit (events.js:400:28)
    at process.<anonymous> (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:400:28)
    at process.emit (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/node_modules/source-map-support/source-map-support.js:495:21)
    at processEmit [as emit] (/project/node_modules/signal-exit/index.js:197:34)
    at emit (internal/child_process.js:912:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)

```

Looking at the file https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/v4.3.1/lib/getConfig.js#L7
I changed it to

```javascript
const cosmiconfig = require("cosmiconfig");

let explorer;

exports.getConfig = () => {
  if (!explorer) {
    // BUG
    // explorer = cosmiconfig("cypress-cucumber-preprocessor", {
    explorer = cosmiconfig.cosmiconfig("cypress-cucumber-preprocessor", {
      sync: true,
      rcExtensions: true,
    });
  }

  const loaded = explorer.load();
  return loaded && loaded.config;
};
```

### Desired behavior

No error should be thrown

### Test code to reproduce

See above

### Versions

* **Cypress version**: 9.4.1
* **Preprocessor version**: 4.3.1
* **Node version**: 14.19.0

**Comment by badeball** [comment]
I'm not convinced that this is really an issue with the preprocessor, but that rather that you have the wrong version of cosmiconfig installed (why I can't say).

**Comment by WinstonN** [comment]
Installing cosmiconfig `"version": "4.0.0",` resolves the issue. Seems like an update to cosmiconfig causes the issue
