### ISSUE TITLE
Error: load must pass a non-empty string

### ISSUE THREAD

**Issue by WinstonN** [TheBrainFamily/cypress-cucumber-preprocessor#684]
### Current behavior

Following the instructions on integrating cypress-cucumber-preprocessor with cypress, I see the following error when I click on a spec file

```bash
Error: load must pass a non-empty string
    at Explorer.validateFilePath (/projects/node_modules/cosmiconfig/src/ExplorerBase.ts:132:13)
    at Explorer.load (/projects/node_modules/cosmiconfig/src/Explorer.ts:96:10)
    at exports.getConfig (/projects/node_modules/cypress-cucumber-preprocessor/lib/getConfig.js:13:27)
    at module.exports (/projects/node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.js:7:18)
    at Object.handler (/projects/node_modules/cypress-cucumber-preprocessor/lib/index.js:78:16)
    at invoke (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:22:16)
    at /home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/util.js:45:14
    at tryCatcher (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/util.js:44:23)
    at Object.wrap (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/preprocessor.js:28:8)
    at execute (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:119:27)
    at EventEmitter.<anonymous> (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:209:5)
    at EventEmitter.emit (events.js:400:28)
    at process.<anonymous> (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:400:28)
    at process.emit (/home/win/.cache/Cypress/9.4.1/Cypress/resources/app/node_modules/source-map-support/source-map-support.js:495:21)
    at processEmit [as emit] (/projects/node_modules/signal-exit/index.js:197:34)
    at emit (internal/child_process.js:912:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

My plugin file looks like 

```javascript
/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

const backstop = require('backstopjs');
const config = require('../../backstop.json');
const cucumber = require('cypress-cucumber-preprocessor').default

/**
 * Run BackstopJS as code
 * Scenarios and Report folder name can be set via params
 */
function backstopExec(payload = {scenarios: [], folder:'default'}, refreshReferences = true) {
  return new Promise((resolve) => {
    const configuration = config
    config.scenarios = payload.scenarios
    config.paths.html_report = `cypress/artefacts/reports/backstop/${payload.folder}/html_report`
    config.paths.ci_report = `cypress/artefacts/reports/backstop/${payload.folder}/ci_report`

    if (refreshReferences) {
      backstop('reference', { config: configuration }).then(() => {
        resolve(null)
      }).catch(() => {
        resolve(null)
      })
    } else {
      backstop('test', { config: configuration }).then(() => {
        resolve(null)
      }).catch(() => {
        resolve(null)
      })
    }

  })
}

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on, config) => {
  /** backstop js begin */
  backstop('init')

  on('task', {
    log(message) {
      console.log(message)
      return null
    },
    backstopRefreshReferences(customConfig) {
      return backstopExec(customConfig)
    },
    backstopTest(customConfig) {
      return backstopExec(customConfig, false)
    }
  })
  /** backstop js end */

  /** cucumber begin */
  on('file:preprocessor', cucumber())
  /** cucumber end */

  return config;
};

```
### Desired behavior

No error should be thrown

### Test code to reproduce

See above

### Versions

* **Cypress version**: 9.4.1
* **Preprocessor version**: 4.3.1
* **Node version**: 14.19.0

**Comment by WinstonN** [comment]
After dropping down to an earlier version of cosmiconfig see #683 this error went away
