### ISSUE TITLE
fs-events windows 10

### ISSUE THREAD

**Issue by dvelasquez** [TheBrainFamily/cypress-cucumber-preprocessor#73]
I'm trying to run a feature using Windows 10 and cypress is throwing the following error:

```
The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.

Error: Cannot find module 'fsevents' from 'C:\Users\Danilo Velasquez\dev\altiro-seed\node_modules\chokidar\lib'
at C:\Users\Danilo Velasquez\dev\altiro-seed\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
at process (C:\Users\Danilo Velasquez\dev\altiro-seed\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
at ondir (C:\Users\Danilo Velasquez\dev\altiro-seed\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
at load (C:\Users\Danilo Velasquez\dev\altiro-seed\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
at onex (C:\Users\Danilo Velasquez\dev\altiro-seed\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
at C:\Users\Danilo Velasquez\dev\altiro-seed\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
at C:\Users\Danilo Velasquez\AppData\Local\Cypress\Cache\3.0.2\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:284:29
at FSReqWrap.oncomplete (fs.js:152:21)
```
I'm not sure if this problem is related to the configuration, cypress or the plugin.

**Comment by dvelasquez** [comment]
Sure, I'll give it a try later today.

**Comment by lgandecki** [comment]
Hello 👋 @dvelasquez Would you be able to verify this? :) I'm doing some cleaning around this repo

**Comment by dvelasquez** [comment]
Hi @igandecki after a lot of frustrations we decide to drop Cypress and use Selenium for our e2e testing.
The problem wasn't this plugin but the continuous breaking changed introduced by Cypress.

Anyway, thanks for the follow up.
